/**
 * Ingredient Metadata - Minimal stub
 * Add your own dataset to populate INGREDIENT_METADATA
 */

export interface IngredientMetadata {
  emoji: string;
  category: string;
  label: string;
}

export const INGREDIENT_CATEGORIES = {
  FRUITS: "Meyveler",
  VEGETABLES: "Sebzeler",
  MEAT_POULTRY: "Et & Kümes Hayvanları",
  SEAFOOD: "Deniz Ürünleri",
  DAIRY_EGGS: "Süt Ürünleri & Yumurta",
  GRAINS: "Tahıllar & Makarna",
  SPICES: "Baharatlar & Otlar",
  BAKERY: "Fırın Ürünleri",
  NUTS: "Kuruyemiş & Tohumlar",
  LEGUMES: "Baklagiller",
  BEVERAGES: "İçecekler",
  SAUCES: "Soslar & Çeşniler",
  OILS: "Yağlar",
  SWEETS: "Tatlılar",
  PRESERVED: "Konserveler & Turşular",
  OTHER: "Diğer",
} as const;

export const CATEGORY_EMOJIS: Record<string, string> = {
  [INGREDIENT_CATEGORIES.FRUITS]: "🍎",
  [INGREDIENT_CATEGORIES.VEGETABLES]: "🥦",
  [INGREDIENT_CATEGORIES.MEAT_POULTRY]: "🥩",
  [INGREDIENT_CATEGORIES.SEAFOOD]: "🐟",
  [INGREDIENT_CATEGORIES.DAIRY_EGGS]: "🥛",
  [INGREDIENT_CATEGORIES.GRAINS]: "🌾",
  [INGREDIENT_CATEGORIES.SPICES]: "🧂",
  [INGREDIENT_CATEGORIES.BAKERY]: "🍞",
  [INGREDIENT_CATEGORIES.NUTS]: "🥜",
  [INGREDIENT_CATEGORIES.LEGUMES]: "🫘",
  [INGREDIENT_CATEGORIES.BEVERAGES]: "🍷",
  [INGREDIENT_CATEGORIES.SAUCES]: "🍯",
  [INGREDIENT_CATEGORIES.OILS]: "🧈",
  [INGREDIENT_CATEGORIES.SWEETS]: "🍰",
  [INGREDIENT_CATEGORIES.PRESERVED]: "🥫",
  [INGREDIENT_CATEGORIES.OTHER]: "🥘",
};

const C = INGREDIENT_CATEGORIES;

export const INGREDIENT_METADATA: Record<string, IngredientMetadata> = {
  tuz: { emoji: "🧂", category: C.SPICES, label: "Tuz" },
  soğan: { emoji: "🧅", category: C.VEGETABLES, label: "Soğan" },
  karabiber: { emoji: "🫙", category: C.SPICES, label: "Karabiber" },
  zeytinyağı: { emoji: "🫒", category: C.OILS, label: "Zeytinyağı" },
  su: { emoji: "💧", category: C.BEVERAGES, label: "Su" },
  "pul biber": { emoji: "🌶️", category: C.SPICES, label: "Pul Biber" },
  tereyağı: { emoji: "🧈", category: C.OILS, label: "Tereyağı" },
  "toz şeker": { emoji: "🍚", category: C.SWEETS, label: "Toz Şeker" },
  domates: { emoji: "🍅", category: C.VEGETABLES, label: "Domates" },
  "domates salçası": { emoji: "🥫", category: C.SAUCES, label: "Domates Salçası" },
  yumurta: { emoji: "🥚", category: C.DAIRY_EGGS, label: "Yumurta" },
  un: { emoji: "🌾", category: C.GRAINS, label: "Un" },
  patates: { emoji: "🥔", category: C.VEGETABLES, label: "Patates" },
  sarımsak: { emoji: "🧄", category: C.VEGETABLES, label: "Sarımsak" },
  "sivri biber": { emoji: "🌶️", category: C.VEGETABLES, label: "Sivri Biber" },
  limon: { emoji: "🍋", category: C.FRUITS, label: "Limon" },
  maydanoz: { emoji: "🌿", category: C.SPICES, label: "Maydanoz" },
  vanilya: { emoji: "🌿", category: C.SPICES, label: "Vanilya" },
  pirinç: { emoji: "🍚", category: C.GRAINS, label: "Pirinç" },
  süt: { emoji: "🥛", category: C.DAIRY_EGGS, label: "Süt" },
  kimyon: { emoji: "🧂", category: C.SPICES, label: "Kimyon" },
  "mısır unu": { emoji: "🌽", category: C.GRAINS, label: "Mısır Unu" },
  "biber salçası": { emoji: "🥫", category: C.SAUCES, label: "Biber Salçası" },
  kıyma: { emoji: "🥩", category: C.MEAT_POULTRY, label: "Kıyma" },
  nane: { emoji: "🌿", category: C.SPICES, label: "Nane" },
  "yulaf sütü": { emoji: "🥛", category: C.BEVERAGES, label: "Yulaf Sütü" },
  "limon suyu": { emoji: "🍋", category: C.BEVERAGES, label: "Limon Suyu" },
  kekik: { emoji: "🌿", category: C.SPICES, label: "Kekik" },
  "kızartma yağı": { emoji: "🫗", category: C.OILS, label: "Kızartma Yağı" },
  "mısır nişastası": { emoji: "🌽", category: C.GRAINS, label: "Mısır Nişastası" },
  yoğurt: { emoji: "🥛", category: C.DAIRY_EGGS, label: "Yoğurt" },
  patlıcan: { emoji: "🍆", category: C.VEGETABLES, label: "Patlıcan" },
  "yaş maya": { emoji: "🧪", category: C.BAKERY, label: "Yaş Maya" },
  şeker: { emoji: "🍚", category: C.SWEETS, label: "Şeker" },
  havuç: { emoji: "🥕", category: C.VEGETABLES, label: "Havuç" },
  "sıvı yağ": { emoji: "🫗", category: C.OILS, label: "Sıvı Yağ" },
  "kabartma tozu": { emoji: "🧪", category: C.BAKERY, label: "Kabartma Tozu" },
  yufka: { emoji: "🥟", category: C.BAKERY, label: "Yufka" },
  dereotu: { emoji: "🌿", category: C.SPICES, label: "Dereotu" },
  margarin: { emoji: "🧈", category: C.OILS, label: "Margarin" },
  "beyaz peynir": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Beyaz Peynir" },
  "pirinç unu": { emoji: "🌾", category: C.GRAINS, label: "Pirinç Unu" },
  "dana eti": { emoji: "🥩", category: C.MEAT_POULTRY, label: "Dana Eti" },
  "kuzu eti": { emoji: "🥩", category: C.MEAT_POULTRY, label: "Kuzu Eti" },
  "kırmızı mercimek": { emoji: "🫘", category: C.LEGUMES, label: "Kırmızı Mercimek" },
  nişasta: { emoji: "🌽", category: C.GRAINS, label: "Nişasta" },
  nohut: { emoji: "🫘", category: C.LEGUMES, label: "Nohut" },
  ceviz: { emoji: "🥜", category: C.NUTS, label: "Ceviz" },
  "glutensiz un karışımı": { emoji: "🌾", category: C.GRAINS, label: "Glutensiz Un Karışımı" },
  lavaş: { emoji: "🫓", category: C.BAKERY, label: "Lavaş" },
  "nar ekşisi": { emoji: "🍯", category: C.SAUCES, label: "Nar Ekşisi" },
  "sebze suyu": { emoji: "🥣", category: C.BEVERAGES, label: "Sebze Suyu" },
  kakao: { emoji: "🍫", category: C.SWEETS, label: "Kakao" },
  "instant maya": { emoji: "🧪", category: C.BAKERY, label: "Instant Maya" },
  irmik: { emoji: "🌾", category: C.GRAINS, label: "İrmik" },
  "tavuk suyu": { emoji: "🍲", category: C.BEVERAGES, label: "Tavuk Suyu" },
  kabak: { emoji: "🎃", category: C.VEGETABLES, label: "Kabak" },
  "kaşar peyniri": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Kaşar Peyniri" },
  sirke: { emoji: "🍶", category: C.SAUCES, label: "Sirke" },
  tarçın: { emoji: "🫙", category: C.SPICES, label: "Tarçın" },
  "tavuk göğsü": { emoji: "🍗", category: C.MEAT_POULTRY, label: "Tavuk Göğsü" },
  biber: { emoji: "🌶️", category: C.VEGETABLES, label: "Biber" },
  bulgur: { emoji: "🌾", category: C.GRAINS, label: "Bulgur" },
  "dana kıyma": { emoji: "🥩", category: C.MEAT_POULTRY, label: "Dana Kıyma" },
  "istiridye mantarı": { emoji: "🍄", category: C.VEGETABLES, label: "İstiridye Mantarı" },
  "soya kıyma": { emoji: "🫘", category: C.LEGUMES, label: "Soya Kıyma" },
  zerdeçal: { emoji: "🫙", category: C.SPICES, label: "Zerdeçal" },
  "bayat ekmek": { emoji: "🍞", category: C.BAKERY, label: "Bayat Ekmek" },
  tahin: { emoji: "🥜", category: C.SAUCES, label: "Tahin" },
  "tavuk but": { emoji: "🍗", category: C.MEAT_POULTRY, label: "Tavuk But" },
  "yeşil soğan": { emoji: "🧅", category: C.VEGETABLES, label: "Yeşil Soğan" },
  bezelye: { emoji: "🫛", category: C.VEGETABLES, label: "Bezelye" },
  "kuru fasulye": { emoji: "🫘", category: C.LEGUMES, label: "Kuru Fasulye" },
  sumak: { emoji: "🫙", category: C.SPICES, label: "Sumak" },
  "çörek otu": { emoji: "🌿", category: C.SPICES, label: "Çörek Otu" },
  ıspanak: { emoji: "🥬", category: C.VEGETABLES, label: "Ispanak" },
  "badem sütü": { emoji: "🥛", category: C.BEVERAGES, label: "Badem Sütü" },
  "baklava yufkası": { emoji: "🥟", category: C.BAKERY, label: "Baklava Yufkası" },
  "gül suyu": { emoji: "🌸", category: C.SWEETS, label: "Gül Suyu" },
  tofu: { emoji: "🧈", category: C.LEGUMES, label: "Tofu" },
  "yumurta sarısı": { emoji: "🥚", category: C.DAIRY_EGGS, label: "Yumurta Sarısı" },
  "hindistan cevizi": { emoji: "🥥", category: C.NUTS, label: "Hindistan Cevizi" },
  "hindistan cevizi sütü": { emoji: "🥥", category: C.BEVERAGES, label: "Hindistan Cevizi Sütü" },
  "ince bulgur": { emoji: "🌾", category: C.GRAINS, label: "İnce Bulgur" },
  krema: { emoji: "🥛", category: C.DAIRY_EGGS, label: "Krema" },
  nar: { emoji: "🍎", category: C.FRUITS, label: "Nar" },
  pekmez: { emoji: "🍯", category: C.SWEETS, label: "Pekmez" },
  "soya yoğurdu": { emoji: "🥛", category: C.DAIRY_EGGS, label: "Soya Yoğurdu" },
  susam: { emoji: "🥜", category: C.NUTS, label: "Susam" },
  "tel kadayıf": { emoji: "🥟", category: C.BAKERY, label: "Tel Kadayıf" },
  "vegan kaşar": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Vegan Kaşar" },
  çilek: { emoji: "🍓", category: C.FRUITS, label: "Çilek" },
  "et suyu": { emoji: "🍲", category: C.BEVERAGES, label: "Et Suyu" },
  "hindistan cevizi krema": { emoji: "🥥", category: C.DAIRY_EGGS, label: "Hindistan Cevizi Krema" },
  karabuğday: { emoji: "🌾", category: C.GRAINS, label: "Karabuğday" },
  "kuru üzüm": { emoji: "🍇", category: C.FRUITS, label: "Kuru Üzüm" },
  "lor peyniri": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Lor Peyniri" },
  salatalık: { emoji: "🥒", category: C.VEGETABLES, label: "Salatalık" },
  "soya kuşbaşı": { emoji: "🫘", category: C.LEGUMES, label: "Soya Kuşbaşı" },
  "çam fıstığı": { emoji: "🥜", category: C.NUTS, label: "Çam Fıstığı" },
  "antep fıstığı": { emoji: "🥜", category: C.NUTS, label: "Antep Fıstığı" },
  "güllaç yaprağı": { emoji: "🥟", category: C.BAKERY, label: "Güllaç Yaprağı" },
  karides: { emoji: "🦐", category: C.SEAFOOD, label: "Karides" },
  "kuş üzümü": { emoji: "🍇", category: C.FRUITS, label: "Kuş Üzümü" },
  marul: { emoji: "🥬", category: C.VEGETABLES, label: "Marul" },
  muz: { emoji: "🍌", category: C.FRUITS, label: "Muz" },
  mısır: { emoji: "🌽", category: C.VEGETABLES, label: "Mısır" },
  "taze fasulye": { emoji: "🫛", category: C.VEGETABLES, label: "Taze Fasulye" },
  turşu: { emoji: "🥒", category: C.PRESERVED, label: "Turşu" },
  "vegan bitter çikolata": { emoji: "🍫", category: C.SWEETS, label: "Vegan Bitter Çikolata" },
  "yeşil mercimek": { emoji: "🫘", category: C.LEGUMES, label: "Yeşil Mercimek" },
  badem: { emoji: "🥜", category: C.NUTS, label: "Badem" },
  barbunya: { emoji: "🫘", category: C.LEGUMES, label: "Barbunya" },
  bisküvi: { emoji: "🍪", category: C.BAKERY, label: "Bisküvi" },
  "bitter çikolata": { emoji: "🍫", category: C.SWEETS, label: "Bitter Çikolata" },
  buğday: { emoji: "🌾", category: C.GRAINS, label: "Buğday" },
  börülce: { emoji: "🫘", category: C.LEGUMES, label: "Börülce" },
  ekmek: { emoji: "🍞", category: C.BAKERY, label: "Ekmek" },
  firik: { emoji: "🌾", category: C.GRAINS, label: "Firik" },
  "glutensiz tarhana": { emoji: "🥣", category: C.GRAINS, label: "Glutensiz Tarhana" },
  kereviz: { emoji: "🥬", category: C.VEGETABLES, label: "Kereviz" },
  kinoa: { emoji: "🌾", category: C.GRAINS, label: "Kinoa" },
  "kuru kayısı": { emoji: "🍑", category: C.FRUITS, label: "Kuru Kayısı" },
  "kırmızı biber": { emoji: "🌶️", category: C.VEGETABLES, label: "Kırmızı Biber" },
  "limon kabuğu": { emoji: "🍋", category: C.FRUITS, label: "Limon Kabuğu" },
  mantar: { emoji: "🍄", category: C.VEGETABLES, label: "Mantar" },
  midye: { emoji: "🦪", category: C.SEAFOOD, label: "Midye" },
  "nori yosunu": { emoji: "🌿", category: C.VEGETABLES, label: "Nori Yosunu" },
  "pudra şekeri": { emoji: "🍚", category: C.SWEETS, label: "Pudra Şekeri" },
  "somon fileto": { emoji: "🐟", category: C.SEAFOOD, label: "Somon Fileto" },
  "soya yoğurt": { emoji: "🥛", category: C.DAIRY_EGGS, label: "Soya Yoğurt" },
  "arpacık soğan": { emoji: "🧅", category: C.VEGETABLES, label: "Arpacık Soğan" },
  "asma yaprağı": { emoji: "🍃", category: C.VEGETABLES, label: "Asma Yaprağı" },
  "aşurelik buğday": { emoji: "🌾", category: C.GRAINS, label: "Aşurelik Buğday" },
  "badem unu": { emoji: "🥜", category: C.GRAINS, label: "Badem Unu" },
  "balık fileto": { emoji: "🐟", category: C.SEAFOOD, label: "Balık Fileto" },
  "bayat pide": { emoji: "🫓", category: C.BAKERY, label: "Bayat Pide" },
  "beyaz lahana": { emoji: "🥬", category: C.VEGETABLES, label: "Beyaz Lahana" },
  "beşamel sos": { emoji: "🥣", category: C.SAUCES, label: "Beşamel Sos" },
  biberiye: { emoji: "🌿", category: C.SPICES, label: "Biberiye" },
  buz: { emoji: "🧊", category: C.OTHER, label: "Buz" },
  "bütün tavuk": { emoji: "🍗", category: C.MEAT_POULTRY, label: "Bütün Tavuk" },
  "damla sakızı": { emoji: "🌿", category: C.SPICES, label: "Damla Sakızı" },
  "dolmalık biber": { emoji: "🫑", category: C.VEGETABLES, label: "Dolmalık Biber" },
  enginar: { emoji: "🥬", category: C.VEGETABLES, label: "Enginar" },
  "galeta unu": { emoji: "🍞", category: C.BAKERY, label: "Galeta Unu" },
  gendime: { emoji: "🌾", category: C.GRAINS, label: "Gendime" },
  "hamburger ekmeği": { emoji: "🍔", category: C.BAKERY, label: "Hamburger Ekmeği" },
  hamsi: { emoji: "🐟", category: C.SEAFOOD, label: "Hamsi" },
  "hindi but": { emoji: "🦃", category: C.MEAT_POULTRY, label: "Hindi But" },
  kalamar: { emoji: "🦑", category: C.SEAFOOD, label: "Kalamar" },
  kaymak: { emoji: "🥛", category: C.DAIRY_EGGS, label: "Kaymak" },
  "kuru bakla": { emoji: "🫘", category: C.LEGUMES, label: "Kuru Bakla" },
  "kuru bamya": { emoji: "🥬", category: C.VEGETABLES, label: "Kuru Bamya" },
  "kuzu bağırsak": { emoji: "🥩", category: C.MEAT_POULTRY, label: "Kuzu Bağırsak" },
  "kuzu but": { emoji: "🥩", category: C.MEAT_POULTRY, label: "Kuzu But" },
  "kuzu döner eti": { emoji: "🥩", category: C.MEAT_POULTRY, label: "Kuzu Döner Eti" },
  "kuzu kol": { emoji: "🥩", category: C.MEAT_POULTRY, label: "Kuzu Kol" },
  "künefe peyniri": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Künefe Peyniri" },
  "midye eti": { emoji: "🦪", category: C.SEAFOOD, label: "Midye Eti" },
  pide: { emoji: "🫓", category: C.BAKERY, label: "Pide" },
  "portakal suyu": { emoji: "🍊", category: C.BEVERAGES, label: "Portakal Suyu" },
  pırasa: { emoji: "🥬", category: C.VEGETABLES, label: "Pırasa" },
  salep: { emoji: "🥣", category: C.BEVERAGES, label: "Salep" },
  semizotu: { emoji: "🥬", category: C.VEGETABLES, label: "Semizotu" },
  sosis: { emoji: "🌭", category: C.MEAT_POULTRY, label: "Sosis" },
  "soya sosu": { emoji: "🍶", category: C.SAUCES, label: "Soya Sosu" },
  sucuk: { emoji: "🌭", category: C.MEAT_POULTRY, label: "Sucuk" },
  "tavuk ciğeri": { emoji: "🍗", category: C.MEAT_POULTRY, label: "Tavuk Ciğeri" },
  "taze bakla": { emoji: "🫛", category: C.LEGUMES, label: "Taze Bakla" },
  "taze barbunya": { emoji: "🫘", category: C.LEGUMES, label: "Taze Barbunya" },
  "taze kaşar peyniri": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Taze Kaşar Peyniri" },
  "tost ekmeği": { emoji: "🍞", category: C.BAKERY, label: "Tost Ekmeği" },
  "uskumru fileto": { emoji: "🐟", category: C.SEAFOOD, label: "Uskumru Fileto" },
  "vegan bisküvi": { emoji: "🍪", category: C.BAKERY, label: "Vegan Bisküvi" },
  yenibahar: { emoji: "🫙", category: C.SPICES, label: "Yenibahar" },
  "yeşil zeytin": { emoji: "🫒", category: C.PRESERVED, label: "Yeşil Zeytin" },
  "yoğunlaştırılmış süt": { emoji: "🥛", category: C.DAIRY_EGGS, label: "Yoğunlaştırılmış Süt" },
  şehriye: { emoji: "🍝", category: C.GRAINS, label: "Şehriye" },
  "agar agar": { emoji: "🧪", category: C.OTHER, label: "Agar Agar" },
  bira: { emoji: "🍺", category: C.BEVERAGES, label: "Bira" },
  "dolmalık fıstık": { emoji: "🥜", category: C.NUTS, label: "Dolmalık Fıstık" },
  "glutensiz ekmek": { emoji: "🍞", category: C.BAKERY, label: "Glutensiz Ekmek" },
  "glutensiz hamburger ekmeği": { emoji: "🍔", category: C.BAKERY, label: "Glutensiz Hamburger Ekmeği" },
  "hindi göğsü": { emoji: "🦃", category: C.MEAT_POULTRY, label: "Hindi Göğsü" },
  işkembe: { emoji: "🥩", category: C.MEAT_POULTRY, label: "İşkembe" },
  jelatin: { emoji: "🧪", category: C.OTHER, label: "Jelatin" },
  karalahana: { emoji: "🥬", category: C.VEGETABLES, label: "Karalahana" },
  "kuru incir": { emoji: "🍇", category: C.FRUITS, label: "Kuru İncir" },
  levrek: { emoji: "🐟", category: C.SEAFOOD, label: "Levrek" },
  "levrek fileto": { emoji: "🐟", category: C.SEAFOOD, label: "Levrek Fileto" },
  "maraş tarhanası": { emoji: "🥣", category: C.GRAINS, label: "Maraş Tarhanası" },
  mayonez: { emoji: "🥫", category: C.SAUCES, label: "Mayonez" },
  "mezgit fileto": { emoji: "🐟", category: C.SEAFOOD, label: "Mezgit Fileto" },
  "mısır gevreği kırığı": { emoji: "🌽", category: C.GRAINS, label: "Mısır Gevreği Kırığı" },
  "mısır tortilla": { emoji: "🫓", category: C.BAKERY, label: "Mısır Tortilla" },
  palamut: { emoji: "🐟", category: C.SEAFOOD, label: "Palamut" },
  pastırma: { emoji: "🥩", category: C.MEAT_POULTRY, label: "Pastırma" },
  "penne makarna": { emoji: "🍝", category: C.GRAINS, label: "Penne Makarna" },
  soda: { emoji: "🥤", category: C.BEVERAGES, label: "Soda" },
  "süzme yoğurt": { emoji: "🥛", category: C.DAIRY_EGGS, label: "Süzme Yoğurt" },
  tarhana: { emoji: "🥣", category: C.GRAINS, label: "Tarhana" },
  "tavuk baget": { emoji: "🍗", category: C.MEAT_POULTRY, label: "Tavuk Baget" },
  "tavuk kanat": { emoji: "🍗", category: C.MEAT_POULTRY, label: "Tavuk Kanat" },
  "tavuk pirzola": { emoji: "🍗", category: C.MEAT_POULTRY, label: "Tavuk Pirzola" },
  "trabzon peyniri": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Trabzon Peyniri" },
  "tuzsuz lor": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Tuzsuz Lor" },
  "vegan beyaz peynir": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Vegan Beyaz Peynir" },
  "yeşil biber": { emoji: "🌶️", category: C.VEGETABLES, label: "Yeşil Biber" },
  "yeşil domates": { emoji: "🍅", category: C.VEGETABLES, label: "Yeşil Domates" },
  "çeçil peyniri": { emoji: "🧀", category: C.DAIRY_EGGS, label: "Çeçil Peyniri" },
  "çiğ köftelik bulgur": { emoji: "🌾", category: C.GRAINS, label: "Çiğ Köftelik Bulgur" },
};

export function getIngredientDetails(name: string): IngredientMetadata {
  const normalizedName = name.toLowerCase().trim();
  if (INGREDIENT_METADATA[normalizedName]) {
    return INGREDIENT_METADATA[normalizedName];
  }
  return {
    emoji: "🥘",
    category: INGREDIENT_CATEGORIES.OTHER,
    label: name.charAt(0).toUpperCase() + name.slice(1),
  };
}

export function groupIngredientsByCategory(ingredientNames: string[]): Record<string, string[]> {
  const grouped: Record<string, string[]> = {};
  ingredientNames.forEach((name) => {
    const details = getIngredientDetails(name);
    if (!grouped[details.category]) {
      grouped[details.category] = [];
    }
    grouped[details.category].push(name);
  });
  return grouped;
}

export function sortCategories(categories: string[]): string[] {
  const otherCategory = categories.find(
    (cat) =>
      cat === INGREDIENT_CATEGORIES.OTHER ||
      cat.toLowerCase().includes("other")
  );
  const nonOtherCategories = categories.filter(
    (cat) =>
      !otherCategory ||
      (cat !== otherCategory && !cat.toLowerCase().includes("other"))
  );
  nonOtherCategories.sort((a, b) => a.localeCompare(b));
  const result = [...nonOtherCategories];
  if (otherCategory) result.push(otherCategory);
  return result;
}
